/** @type {import('tailwindcss').Config} */
import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#e2e2e2",
        "on-secondary-fixed": "#1a1c1c",
        "on-primary": "#690002",
        background: "#210e0c",
        "on-tertiary-fixed": "#001d33",
        outline: "#b08781",
        "cockpit-surface": "#152031",
        primary: "#ffb4a9",
        "tertiary-container": "#2b96e5",
        "on-background": "#ffdad5",
        "on-primary-container": "#5c0002",
        "primary-fixed-dim": "#ffb4a9",
        "error-container": "#93000a",
        "tertiary-fixed": "#cfe5ff",
        "surface-container-highest": "#462f2c",
        "surface-dim": "#210e0c",
        secondary: "#c6c6c7",
        "on-primary-fixed-variant": "#930005",
        "secondary-container": "#454747",
        "surface-container-lowest": "#1b0907",
        "vibrant-red": "#ff1a1a",
        error: "#ffb4ab",
        "on-tertiary-container": "#002c4a",
        "on-surface": "#ffdad5",
        "on-error-container": "#ffdad6",
        "surface-bright": "#4b3330",
        "on-surface-variant": "#eabcb5",
        "surface-container": "#2f1a17",
        "cockpit-base": "#081425",
        "inverse-primary": "#c00009",
        "outline-variant": "#5f3e3a",
        "primary-fixed": "#ffdad5",
        "primary-container": "#ff5545",
        "on-secondary-container": "#b4b5b5",
        "secondary-fixed-dim": "#c6c6c7",
        tertiary: "#99cbff",
        "surface-container-high": "#3a2421",
        surface: "#210e0c",
        "on-error": "#690005",
        "surface-tint": "#ffb4a9",
        "on-tertiary-fixed-variant": "#004a78",
        "on-secondary-fixed-variant": "#454747",
        "surface-variant": "#462f2c",
        "surface-container-low": "#2a1614",
        "on-tertiary": "#003354",
        "inverse-on-surface": "#412b27",
        "on-primary-fixed": "#410001",
        "inverse-surface": "#ffdad5",
        "tertiary-fixed-dim": "#99cbff",
        "on-secondary": "#2f3131",
        "alert-yellow": "#ffcc00",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "40px",
        gutter: "12px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        xs: "4px",
        base: "4px",
      },
      fontFamily: {
        "display-multiplier": ["Sora"],
        "headline-lg-mobile": ["Sora"],
        "label-mono": ["JetBrains Mono"],
        "label-caps": ["Inter"],
        "technical-mono": ["JetBrains Mono"],
        "headline-md": ["Sora"],
        "headline-sm": ["Sora"],
        "body-md": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "headline-lg": ["Sora"],
      },
      fontSize: {
        "display-multiplier": [
          "72px",
          { lineHeight: "72px", letterSpacing: "-0.04em", fontWeight: "800" },
        ],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "label-mono": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "700" }],
        "technical-mono": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
      },
    },
  },
  plugins: [forms, containerQueries],
};
